version: 0.1

arch: armhf
build-directory: output/

env:
        variables:
                OS: linux

phases:
        installs:
                - image: debian
                  mirror: http://deb.debian.org/debian/
                  name: hello-world_python3_debian-buster_armhf
                  cache: "save,reuse"
                  commands:
                        - ["echo", "Installed debian buster"]
                        - ["apt-get", "update"]
                        - ["apt-get", "install", "-y", "--no-install-recommends",
                          "build-essential", "pkg-config", "ca-certificates",
                          "curl", "netbase", "wget", "git",
                          "openssh-client", "python", "gnupg" ]
                        # On armhf we have to rehash certificates for openssl tools
                        - ["c_rehash" ]
                        - ["update-ca-certificates" ]
                        - ["rm", "-rf", "/var/lib/apt/lists/*" ]
                        - ["rm", "-rf", "/var/cache/apt/archives/partial/" ]
                        - ["echo", "Installed debian build devtools packages" ]


        builds:
                # Set what image to use from installs
                - use: hello-world_python3_debian-buster_armhf
                  commands:
                        - ["script", "python3-install.sh"]
                        - ["rm", "-rf", "/var/lib/apt/lists/*"]
                        - ["rm", "-rf", "/var/cache/apt/archives/partial/"]
                        - ["/bin/bash", "-c", "echo $(python3 --version) installed"]

artifacts:
        - use: hello-world_python3_debian-buster_armhf
          name: hello-world_python3_debian-buster_armhf
          files:
                # copy app.yaml to root artifact /app.yaml
                - app.yaml /app.yaml

                # copy my application
                - hello-world.py  /usr/bin/hello-world.py

          compression: tar
