version: 0.1

arch: armhf
base-directory: build/

phases:
        installs:
                - image: debian
                  mirror: http://deb.debian.org/debian/
                  release: stretch
                  name: debian-armhf-dev
                  cache: "reuse"
                  install-args:
                  runtime-versions:
                  commands:
                        - echo "Installed debian stretch"
                        - copy LICENSE /opt/
                        - cat /etc/os-release
                        - echo "OS release file output above"

                - image: debian
                  mirror: http://deb.debian.org/debian/
                  release: stretch
                  name: debian-armhf-prod
                  cache: "reuse"
                  install-args:


        pre-builds:
                # Set what image to use from installs
                - use: debian-armhf-dev
                  commands:
                        - echo "Build programs started"
                        - cat /etc/os-release

        builds:
                # Set what image to use from installs
                - use: debian-armhf-dev
                  commands:
                        - echo "Build stage and programs"
                        - cat /etc/os-release

                # Use debian-armhf-prod image as target
                - use: debian-armhf-prod
                  commands:
                        # copy from dev image to prod image
                        - copy --from=debian-armhf-dev /opt/LICENSE /opt/
                        - cat /etc/os-release

        post-builds:
                - use: debian-armhf-prod
                  commands:
                        - echo "Build production finished"

artifacts:
        - name: debian-stretch-armhf
          suffix: date +%Y-%m-%d
          files:
                - debian-armhf-prod
          compression: tar
