version: 0.1

arch: armhf
build-directory: output/

phases:
        installs:
                - image: debian
                  mirror: http://deb.debian.org/debian/
                  release: buster
                  name: devtools_debian-buster_armhf
                  cache: "save,reuse"
                  install-args:
                  runtime-versions:
                  commands:
                        - ["echo", "Installed debian buster" ]
                        - ["apt-get", "update" ]
                        - ["apt-get", "install", "-y", "--no-install-recommends",
                          "build-essential", "pkg-config", "ca-certificates",
                          "curl", "netbase", "wget", "git", "mercurial", "file",
                          "openssh-client", "subversion", "gnupg", "dirmngr", "procps" ]
                        # On armhf we have to rehash certificates for openssl tools
                        - ["c_rehash" ]
                        - ["update-ca-certificates" ]
                        - ["rm", "-rf", "/var/lib/apt/lists/*" ]
                        - ["rm", "-rf", "/var/cache/apt/archives/partial/" ]
                        - ["echo", "Installed debian build devtools packages" ]


artifacts:
        - use: devtools_debian-buster_armhf
          name: devtools_debian-buster_armhf
          compression: tar
