version: 0.1

arch: armhf
build-directory: output/

env:
        variables:
                OS: linux
                NODE_ARCH: "armv7l"

phases:
        installs:
                - image: alpine
                  name: build-base_alpine_armhf
                  cache: "save,reuse"
                  commands:
                        - ["/bin/bash", "-c", "echo Installed alpine mini ARCH=$arch"]
                        - ["cat", "/etc/os-release"]
                        - ["apk", "update"]
                        - ["apk", "add", "ca-certificates", "ssl_client"]
                        - ["apk", "add", "--no-cache", "curl", "tar", "gnupg"]
                        - ["apk", "add", "--no-cache", "--virtual", ".build-deps-full",
                           "build-base", "gcc", "make", "g++", "python3", "linux-headers",
                           "wget", "git"] 
                        - ["rm", "-rf", "/var/cache/apk/*" ]
                        - ["rm", "-rf", "/tmp/*" ]
                        - ["echo", "Installed alpine build base packages" ]


        builds:
                # Set what image to use from installs
                - use: build-base_alpine_armhf
                  commands:
                        # we run script node-install.sh to install
                        # node, the script is the upstream version
                        # and is located in the same directory of
                        # this buildspec file.
                        - ["script", "node-install.sh"]
                        - ["/bin/bash", "-c", "echo installed node $(node --version) version"]

        post-builds:
                - use: build-base_alpine_armhf
                  commands:
                        - ["script", "cleanup-node-install.sh"]


artifacts:
        - use: build-base_alpine_armhf
          name: node_build-base_alpine_armhf
          compression: tar.gz
