version: 0.1

arch: armhf
build-directory: output/

env:
        variables:
                OS: linux
                NODE_ARCH: "armv7l"

phases:
        installs:
                - image: alpine
                  name: minimal_alpine_armhf
                  cache: "save,reuse"
                  commands:
                        - ["/bin/bash", "-c", "echo Installed alpine mini ARCH=$arch"]
                        - ["cat", "/etc/os-release"]
                        - ["apk", "update"]
                        - ["apk", "add", "--no-cache",
                        # "build-base",
                           "ca-certificates", "ssl_client", "curl", "wget", "tar", "gnupg"]
                        - ["rm", "-rf", "/var/cache/apk/*" ]
                        - ["rm", "-rf", "/tmp/*" ]
                        - ["echo", "Installed alpine build base packages" ]


        builds:
                # Set what image to use from installs
                - use: minimal_alpine_armhf
                  commands:
                        # we run script node-install.sh to install
                        # node, the script is the upstream version
                        # and is located in the same directory of
                        # this buildspec file.
                        - ["script", "node-install.sh"]
                        - ["/bin/bash", "-c", "echo installed node $(node --version) version"]

        post-builds:
                - use: minimal_alpine_armhf
                  commands:
                        - ["script", "cleanup-node-install.sh"]

artifacts:
        - use: minimal_alpine_armhf
          name: node_minimal_alpine_armhf
          compression: tar.gz
